#include "globals.hpp"
#include <cmath>

int BATTLE_PASS_CLOSE_POPUP_X = 0;
int BATTLE_PASS_CLOSE_POPUP_Y = 0;
int BATTLE_PASS_CLAIM_ALL_X = 0;
int BATTLE_PASS_CLAIM_ALL_Y = 0;
int BATTLE_PASS_X = 0;
int BATTLE_PASS_Y = 0;
int BATTLE_PASS_CLOSE_X = 0;
int BATTLE_PASS_CLOSE_Y = 0;

int MISSION_MODE_SEE_ALL_X = 0;
int MISSION_MODE_SEE_ALL_Y = 0;
int MISSION_MODE_CLOSE_X = 0;
int MISSION_MODE_CLOSE_Y = 0;

int MISSION_PREVIEW_MODE_SCROLL_X = 0;
int MISSION_PREVIEW_MODE_SCROLL_Y = 0;
int MISSION_PREVIEW_MODE_SCROLL_WIDTH = 0;
int MISSION_PREVIEW_MODE_SCROLL_HEIGHT = 0;

int ATTRIBUTES_DUNGEONS_TAB_X = 0;
int ATTRIBUTES_DUNGEONS_TAB_Y = 0;
int ATTRIBUTES_STATS_TAB_X = 0;
int ATTRIBUTES_STATS_TAB_Y = 0;
int ATTRIBUTES_SCROLL_X = 0;
int ATTRIBUTES_SCROLL_Y = 0;
int ATTRIBUTES_SCROLL_WIDTH = 0;
int ATTRIBUTES_SCROLL_HEIGHT = 0;

int PET_INVENTORY_X = 0;
int PET_INVENTORY_Y = 0;
int PET_INVENTORY_WIDTH = 0;
int PET_INVENTORY_HEIGHT = 0;

int MENUBAR_X = 0;
int MENUBAR_Y = 0;
int MENUBAR_WIDTH = 0;
int MENUBAR_HEIGHT = 0;

int EQUIPMENT_SLOT0_X = 0;
int EQUIPMENT_SLOT0_Y = 0;
int EQUIPMENT_SLOT_WIDTH = 0;
int EQUIPMENT_SLOT_HEIGHT = 0;

int POTION_RACK_SLOT0_X = 0;
int POTION_RACK_SLOT0_Y = 0;
int POTION_RACK_SLOT_OFFSET_X = 0;
int POTION_RACK_SLOT_OFFSET_Y = 0;
int POTION_RACK_SLOT_WIDTH = 0;
int POTION_RACK_SLOT_HEIGHT = 0;

int CENTER_X = 0;
int CENTER_Y = 0;
int RADIUS = 0;

int CHAT_X = 0;
int CHAT_Y = 0;
int CHAT_HEIGHT = 0;
int CHAT_WIDTH = 0;
int CHAT_JOIN_BUTTON_OFFSET_X = 0;
int CHAT_JOIN_BUTTON_OFFSET_Y = 0;
int CHAT_TELEPORT_BUTTON_OFFSET_X = 0;
int CHAT_TELEPORT_BUTTON_OFFSET_Y = 0;

int PICKUP_SLOT0_X = 0;
int PICKUP_SLOT0_Y = 0;
int PICKUP_SLOT_WIDTH = 0;
int PICKUP_SLOT_HEIGHT = 0;

int MAP_CENTER_X = 0;
int MAP_CENTER_Y = 0;
int MAP_RADIUS = 0;
int MAP_TELEPORT_BUTTON_OFFSET_X = 0;
int MAP_TELEPORT_BUTTON_OFFSET_Y = 0;

int INV_SLOT_WIDTH = 0;
int INV_SLOT_HEIGHT = 0;
int INV_SLOT0_X = 0;
int INV_SLOT0_Y = 0;

int EXTRA_SLOT0_WIDTH = 0;
int EXTRA_SLOT0_X = 0;
int EXTRA_SLOT0_Y = 0;

int VAULT_SLOT0_X = 0;
int VAULT_SLOT0_Y = 0;

int SCREEN_WIDTH = Base::SCREEN_WIDTH;
int SCREEN_HEIGHT = Base::SCREEN_HEIGHT;
int SCREEN_CENTER_X = Base::SCREEN_WIDTH / 2;
int SCREEN_CENTER_Y = Base::SCREEN_HEIGHT / 2;

int WHEEL_CENTER_X = Base::SCREEN_WIDTH / 2;
int WHEEL_CENTER_Y = Base::SCREEN_HEIGHT / 2;
int WHEEL_RADIUS = Base::WHEEL_RADIUS;

void initScaledGlobals(const int actualScreenWidth, const int actualScreenHeight) {
    // Assumes RotMG is stretched to fill the whole window/screen (no
    // letterbox/pillarbox bars) — so X and Y each get their own independent
    // scale factor against the 1920x1080 reference. This is what makes
    // arbitrary aspect ratios line up correctly when the game content itself
    // isn't locked to 16:9: e.g. on a 2560x1080 ultrawide, X stretches more
    // than Y instead of one factor being forced to fit both.
    const double sx = static_cast<double>(actualScreenWidth) / Base::SCREEN_WIDTH;
    const double sy = static_cast<double>(actualScreenHeight) / Base::SCREEN_HEIGHT;
    // A pure radius (circular UI element) can't take independent X/Y scaling
    // without turning into an ellipse, so radii use the average of sx/sy as
    // a compromise. If the aspect ratio is far from 16:9 and a circle like
    // MAP_RADIUS looks off, that's the value to hand-tune.
    const double sr = (sx + sy) / 2.0;

    const auto X = [sx](const int v) { return static_cast<int>(std::lround(v * sx)); };
    const auto Y = [sy](const int v) { return static_cast<int>(std::lround(v * sy)); };
    const auto R = [sr](const int v) { return static_cast<int>(std::lround(v * sr)); };

    BATTLE_PASS_CLOSE_POPUP_X = X(Base::BATTLE_PASS_CLOSE_POPUP_X);
    BATTLE_PASS_CLOSE_POPUP_Y = Y(Base::BATTLE_PASS_CLOSE_POPUP_Y);
    BATTLE_PASS_CLAIM_ALL_X = X(Base::BATTLE_PASS_CLAIM_ALL_X);
    BATTLE_PASS_CLAIM_ALL_Y = Y(Base::BATTLE_PASS_CLAIM_ALL_Y);
    BATTLE_PASS_X = X(Base::BATTLE_PASS_X);
    BATTLE_PASS_Y = Y(Base::BATTLE_PASS_Y);
    BATTLE_PASS_CLOSE_X = X(Base::BATTLE_PASS_CLOSE_X);
    BATTLE_PASS_CLOSE_Y = Y(Base::BATTLE_PASS_CLOSE_Y);

    MISSION_MODE_SEE_ALL_X = X(Base::MISSION_MODE_SEE_ALL_X);
    MISSION_MODE_SEE_ALL_Y = Y(Base::MISSION_MODE_SEE_ALL_Y);
    MISSION_MODE_CLOSE_X = X(Base::MISSION_MODE_CLOSE_X);
    MISSION_MODE_CLOSE_Y = Y(Base::MISSION_MODE_CLOSE_Y);

    MISSION_PREVIEW_MODE_SCROLL_X = X(Base::MISSION_PREVIEW_MODE_SCROLL_X);
    MISSION_PREVIEW_MODE_SCROLL_Y = Y(Base::MISSION_PREVIEW_MODE_SCROLL_Y);
    MISSION_PREVIEW_MODE_SCROLL_WIDTH = X(Base::MISSION_PREVIEW_MODE_SCROLL_WIDTH);
    MISSION_PREVIEW_MODE_SCROLL_HEIGHT = Y(Base::MISSION_PREVIEW_MODE_SCROLL_HEIGHT);

    ATTRIBUTES_DUNGEONS_TAB_X = X(Base::ATTRIBUTES_DUNGEONS_TAB_X);
    ATTRIBUTES_DUNGEONS_TAB_Y = Y(Base::ATTRIBUTES_DUNGEONS_TAB_Y);
    ATTRIBUTES_STATS_TAB_X = X(Base::ATTRIBUTES_STATS_TAB_X);
    ATTRIBUTES_STATS_TAB_Y = Y(Base::ATTRIBUTES_STATS_TAB_Y);
    ATTRIBUTES_SCROLL_X = X(Base::ATTRIBUTES_SCROLL_X);
    ATTRIBUTES_SCROLL_Y = Y(Base::ATTRIBUTES_SCROLL_Y);
    ATTRIBUTES_SCROLL_WIDTH = X(Base::ATTRIBUTES_SCROLL_WIDTH);
    ATTRIBUTES_SCROLL_HEIGHT = Y(Base::ATTRIBUTES_SCROLL_HEIGHT);

    PET_INVENTORY_X = X(Base::PET_INVENTORY_X);
    PET_INVENTORY_Y = Y(Base::PET_INVENTORY_Y);
    PET_INVENTORY_WIDTH = X(Base::PET_INVENTORY_WIDTH);
    PET_INVENTORY_HEIGHT = Y(Base::PET_INVENTORY_HEIGHT);

    MENUBAR_X = X(Base::MENUBAR_X);
    MENUBAR_Y = Y(Base::MENUBAR_Y);
    MENUBAR_WIDTH = X(Base::MENUBAR_WIDTH);
    MENUBAR_HEIGHT = Y(Base::MENUBAR_HEIGHT);

    EQUIPMENT_SLOT0_X = X(Base::EQUIPMENT_SLOT0_X);
    EQUIPMENT_SLOT0_Y = Y(Base::EQUIPMENT_SLOT0_Y);
    EQUIPMENT_SLOT_WIDTH = X(Base::EQUIPMENT_SLOT_WIDTH);
    EQUIPMENT_SLOT_HEIGHT = Y(Base::EQUIPMENT_SLOT_HEIGHT);

    POTION_RACK_SLOT0_X = X(Base::POTION_RACK_SLOT0_X);
    POTION_RACK_SLOT0_Y = Y(Base::POTION_RACK_SLOT0_Y);
    POTION_RACK_SLOT_OFFSET_X = X(Base::POTION_RACK_SLOT_OFFSET_X);
    POTION_RACK_SLOT_OFFSET_Y = Y(Base::POTION_RACK_SLOT_OFFSET_Y);
    POTION_RACK_SLOT_WIDTH = X(Base::POTION_RACK_SLOT_WIDTH);
    POTION_RACK_SLOT_HEIGHT = Y(Base::POTION_RACK_SLOT_HEIGHT);

    CENTER_X = X(Base::CENTER_X);
    CENTER_Y = Y(Base::CENTER_Y);
    RADIUS = R(Base::RADIUS);

    CHAT_X = X(Base::CHAT_X);
    CHAT_Y = Y(Base::CHAT_Y);
    CHAT_HEIGHT = Y(Base::CHAT_HEIGHT);
    CHAT_WIDTH = X(Base::CHAT_WIDTH);
    CHAT_JOIN_BUTTON_OFFSET_X = X(Base::CHAT_JOIN_BUTTON_OFFSET_X);
    CHAT_JOIN_BUTTON_OFFSET_Y = Y(Base::CHAT_JOIN_BUTTON_OFFSET_Y);
    CHAT_TELEPORT_BUTTON_OFFSET_X = X(Base::CHAT_TELEPORT_BUTTON_OFFSET_X);
    CHAT_TELEPORT_BUTTON_OFFSET_Y = Y(Base::CHAT_TELEPORT_BUTTON_OFFSET_Y);

    PICKUP_SLOT0_X = X(Base::PICKUP_SLOT0_X);
    PICKUP_SLOT0_Y = Y(Base::PICKUP_SLOT0_Y);
    PICKUP_SLOT_WIDTH = X(Base::PICKUP_SLOT_WIDTH);
    PICKUP_SLOT_HEIGHT = Y(Base::PICKUP_SLOT_HEIGHT);

    MAP_CENTER_X = X(Base::MAP_CENTER_X);
    MAP_CENTER_Y = Y(Base::MAP_CENTER_Y);
    MAP_RADIUS = R(Base::MAP_RADIUS);
    MAP_TELEPORT_BUTTON_OFFSET_X = X(Base::MAP_TELEPORT_BUTTON_OFFSET_X);
    MAP_TELEPORT_BUTTON_OFFSET_Y = Y(Base::MAP_TELEPORT_BUTTON_OFFSET_Y);

    INV_SLOT_WIDTH = X(Base::INV_SLOT_WIDTH);
    INV_SLOT_HEIGHT = Y(Base::INV_SLOT_HEIGHT);
    INV_SLOT0_X = X(Base::INV_SLOT0_X);
    INV_SLOT0_Y = Y(Base::INV_SLOT0_Y);

    EXTRA_SLOT0_WIDTH = X(Base::EXTRA_SLOT0_WIDTH);
    EXTRA_SLOT0_X = X(Base::EXTRA_SLOT0_X);
    EXTRA_SLOT0_Y = Y(Base::EXTRA_SLOT0_Y);

    VAULT_SLOT0_X = X(Base::VAULT_SLOT0_X);
    VAULT_SLOT0_Y = Y(Base::VAULT_SLOT0_Y);

    SCREEN_WIDTH = actualScreenWidth;
    SCREEN_HEIGHT = actualScreenHeight;
    SCREEN_CENTER_X = actualScreenWidth / 2;
    SCREEN_CENTER_Y = actualScreenHeight / 2;

    WHEEL_CENTER_X = actualScreenWidth / 2;
    WHEEL_CENTER_Y = actualScreenHeight / 2;
    WHEEL_RADIUS = R(Base::WHEEL_RADIUS);
}